const TEAL = '#0E5D4E'
const NAVY = '#0A1F3D'
const GOLD = '#F2B705'
const GREEN = '#17A24A'

function job(partial) {
  const location = `${partial.city}, ${partial.provinceCode}`
  return {
    ...partial,
    location,
    salaryLabel: `$${partial.salaryMin.toLocaleString('en-CA')} - $${partial.salaryMax.toLocaleString('en-CA')} / year`,
    employerSlug: partial.employerSlug,
  }
}

export const jobs = [
  job({
    id: 'admin-maple-ridge',
    title: 'Administrative Assistant',
    company: 'Maple Ridge Solutions',
    logoColor: TEAL,
    initials: 'MR',
    city: 'Toronto',
    citySlug: 'toronto',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 45000,
    salaryMax: 55000,
    category: 'Administrative Assistant',
    categorySlug: 'administrative-assistant',
    employerSlug: 'rbc',
    postedDate: '2026-08-12',
    description:
      'Support a busy Toronto office with calendar management, correspondence, and day-to-day coordination for a collaborative administrative team.',
  }),
  job({
    id: 'receptionist-northstar',
    title: 'Front Desk Receptionist',
    company: 'Northstar Offices',
    logoColor: NAVY,
    initials: 'NO',
    city: 'Toronto',
    citySlug: 'toronto',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 40000,
    salaryMax: 48000,
    category: 'Receptionist',
    categorySlug: 'receptionist',
    employerSlug: 'td-bank-group',
    postedDate: '2026-08-14',
    description:
      'Greet clients, manage visitor logs, and keep the lobby running smoothly in a professional downtown office environment.',
  }),
  job({
    id: 'ea-summit',
    title: 'Executive Assistant',
    company: 'Summit Partners',
    logoColor: GOLD,
    initials: 'SP',
    city: 'Calgary',
    citySlug: 'calgary',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '3-5 Years',
    experienceSlug: '3-5-years',
    salaryMin: 65000,
    salaryMax: 80000,
    category: 'Executive Assistant',
    categorySlug: 'executive-assistant',
    employerSlug: 'scotiabank',
    postedDate: '2026-08-10',
    description:
      'Partner with senior leadership on scheduling, board materials, and confidential correspondence across a hybrid Calgary office.',
  }),
  job({
    id: 'office-mgr-harbour',
    title: 'Office Manager',
    company: 'Harbour Lane Group',
    logoColor: GREEN,
    initials: 'HL',
    city: 'Vancouver',
    citySlug: 'vancouver',
    province: 'British Columbia',
    provinceCode: 'BC',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: '5+ Years',
    experienceSlug: '5-plus-years',
    salaryMin: 70000,
    salaryMax: 88000,
    category: 'Office Manager',
    categorySlug: 'office-manager',
    employerSlug: 'telus',
    postedDate: '2026-08-08',
    description:
      'Oversee facilities, vendors, and office operations for a growing Vancouver team that values organization and hospitality.',
  }),
  job({
    id: 'data-entry-prairie',
    title: 'Data Entry Specialist',
    company: 'Prairie Records',
    logoColor: TEAL,
    initials: 'PR',
    city: 'Winnipeg',
    citySlug: 'winnipeg',
    province: 'Manitoba',
    provinceCode: 'MB',
    type: 'Part-time',
    typeSlug: 'part-time',
    mode: 'Remote',
    modeSlug: 'remote',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 36000,
    salaryMax: 42000,
    category: 'Data Entry',
    categorySlug: 'data-entry',
    employerSlug: 'loblaw',
    postedDate: '2026-08-16',
    description:
      'Enter and verify records with a high degree of accuracy. Flexible remote hours for a Canada-wide records team.',
  }),
  job({
    id: 'cs-ottawa',
    title: 'Customer Service Coordinator',
    company: 'Capital Care Offices',
    logoColor: NAVY,
    initials: 'CC',
    city: 'Ottawa',
    citySlug: 'ottawa',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 48000,
    salaryMax: 58000,
    category: 'Customer Service',
    categorySlug: 'customer-service',
    employerSlug: 'sun-life',
    postedDate: '2026-08-11',
    description:
      'Resolve inbound inquiries, update client files, and support a bilingual Ottawa office with calm, professional service.',
  }),
  job({
    id: 'payroll-edmonton',
    title: 'Payroll Clerk',
    company: 'Northern Ledger',
    logoColor: GOLD,
    initials: 'NL',
    city: 'Edmonton',
    citySlug: 'edmonton',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Contract',
    typeSlug: 'contract',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 52000,
    salaryMax: 62000,
    category: 'Payroll Clerk',
    categorySlug: 'payroll-clerk',
    employerSlug: 'rbc',
    postedDate: '2026-08-09',
    description:
      'Process bi-weekly payroll, reconcile timesheets, and support year-end reporting for a mid-size Edmonton employer.',
  }),
  job({
    id: 'hr-support-td',
    title: 'HR Support Coordinator',
    company: 'TD Bank Group',
    logoColor: GREEN,
    initials: 'TD',
    city: 'Toronto',
    citySlug: 'toronto',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 55000,
    salaryMax: 68000,
    category: 'HR Support',
    categorySlug: 'hr-support',
    employerSlug: 'td-bank-group',
    postedDate: '2026-08-15',
    description:
      'Assist with onboarding, employee files, and HR inbox management for a large office talent team across the GTA.',
  }),
  job({
    id: 'admin-telus',
    title: 'Office Coordinator',
    company: 'TELUS',
    logoColor: '#4B2E83',
    initials: 'T',
    city: 'Vancouver',
    citySlug: 'vancouver',
    province: 'British Columbia',
    provinceCode: 'BC',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 50000,
    salaryMax: 61000,
    category: 'Administrative Assistant',
    categorySlug: 'administrative-assistant',
    employerSlug: 'telus',
    postedDate: '2026-08-07',
    description:
      'Coordinate meetings, supplies, and internal communications for a fast-paced Vancouver office team.',
  }),
  job({
    id: 'receptionist-sunlife',
    title: 'Corporate Receptionist',
    company: 'Sun Life',
    logoColor: GOLD,
    initials: 'SL',
    city: 'Toronto',
    citySlug: 'toronto',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Temporary',
    typeSlug: 'temporary',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 42000,
    salaryMax: 50000,
    category: 'Receptionist',
    categorySlug: 'receptionist',
    employerSlug: 'sun-life',
    postedDate: '2026-08-13',
    description:
      'Provide a polished first impression at reception, manage couriers, and support meeting-room bookings downtown.',
  }),
  job({
    id: 'ea-rbc',
    title: 'Senior Executive Assistant',
    company: 'RBC',
    logoColor: '#0B4FA0',
    initials: 'RBC',
    city: 'Toronto',
    citySlug: 'toronto',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '5+ Years',
    experienceSlug: '5-plus-years',
    salaryMin: 78000,
    salaryMax: 95000,
    category: 'Executive Assistant',
    categorySlug: 'executive-assistant',
    employerSlug: 'rbc',
    postedDate: '2026-08-05',
    description:
      'Provide high-level support to executives including travel, stakeholder communications, and confidential project tracking.',
  }),
  job({
    id: 'office-mgr-loblaw',
    title: 'Regional Office Manager',
    company: 'Loblaw Companies Limited',
    logoColor: NAVY,
    initials: 'L',
    city: 'Ottawa',
    citySlug: 'ottawa',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: '5+ Years',
    experienceSlug: '5-plus-years',
    salaryMin: 72000,
    salaryMax: 90000,
    category: 'Office Manager',
    categorySlug: 'office-manager',
    employerSlug: 'loblaw',
    postedDate: '2026-08-04',
    description:
      'Lead office operations, vendor relationships, and workplace experience for a regional administrative hub.',
  }),
  job({
    id: 'data-entry-calgary',
    title: 'Records & Data Clerk',
    company: 'Foothills Admin Co.',
    logoColor: TEAL,
    initials: 'FA',
    city: 'Calgary',
    citySlug: 'calgary',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Internship',
    typeSlug: 'internship',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 32000,
    salaryMax: 38000,
    category: 'Data Entry',
    categorySlug: 'data-entry',
    employerSlug: 'scotiabank',
    postedDate: '2026-08-17',
    description:
      'Paid internship supporting digital records, scanning, and quality checks in a structured Calgary office.',
  }),
  job({
    id: 'cs-remote',
    title: 'Remote Office Support Agent',
    company: 'Coastal Connect',
    logoColor: GREEN,
    initials: 'CC',
    city: 'Vancouver',
    citySlug: 'vancouver',
    province: 'British Columbia',
    provinceCode: 'BC',
    type: 'Part-time',
    typeSlug: 'part-time',
    mode: 'Remote',
    modeSlug: 'remote',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 38000,
    salaryMax: 46000,
    category: 'Customer Service',
    categorySlug: 'customer-service',
    employerSlug: 'telus',
    postedDate: '2026-08-18',
    description:
      'Answer tickets, update CRMs, and support office clients remotely with clear written and verbal communication.',
  }),
  job({
    id: 'payroll-winnipeg',
    title: 'Payroll Administrator',
    company: 'Red River Services',
    logoColor: NAVY,
    initials: 'RR',
    city: 'Winnipeg',
    citySlug: 'winnipeg',
    province: 'Manitoba',
    provinceCode: 'MB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: '3-5 Years',
    experienceSlug: '3-5-years',
    salaryMin: 58000,
    salaryMax: 70000,
    category: 'Payroll Clerk',
    categorySlug: 'payroll-clerk',
    employerSlug: 'loblaw',
    postedDate: '2026-08-02',
    description:
      'Own payroll cycles, statutory remittances, and employee inquiries for a Winnipeg-based operations office.',
  }),
  job({
    id: 'hr-edmonton',
    title: 'People Operations Assistant',
    company: 'Prairie People Hub',
    logoColor: GOLD,
    initials: 'PP',
    city: 'Edmonton',
    citySlug: 'edmonton',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Contract',
    typeSlug: 'contract',
    mode: 'Remote',
    modeSlug: 'remote',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 50000,
    salaryMax: 60000,
    category: 'HR Support',
    categorySlug: 'hr-support',
    employerSlug: 'sun-life',
    postedDate: '2026-08-01',
    description:
      'Coordinate interviews, offer letters, and HRIS updates for a distributed Alberta people team.',
  }),
  job({
    id: 'admin-ottawa',
    title: 'Administrative Coordinator',
    company: 'Rideau Admin Partners',
    logoColor: TEAL,
    initials: 'RA',
    city: 'Ottawa',
    citySlug: 'ottawa',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 47000,
    salaryMax: 56000,
    category: 'Administrative Assistant',
    categorySlug: 'administrative-assistant',
    employerSlug: 'rbc',
    postedDate: '2026-07-30',
    description:
      'Keep projects on track with agendas, minutes, travel bookings, and document control for a federal-adjacent office.',
  }),
  job({
    id: 'receptionist-calgary',
    title: 'Office Receptionist',
    company: 'Bow Valley Offices',
    logoColor: NAVY,
    initials: 'BV',
    city: 'Calgary',
    citySlug: 'calgary',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Part-time',
    typeSlug: 'part-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 34000,
    salaryMax: 40000,
    category: 'Receptionist',
    categorySlug: 'receptionist',
    employerSlug: 'scotiabank',
    postedDate: '2026-08-06',
    description:
      'Part-time front desk coverage including calls, mail, and visitor hospitality in a downtown Calgary tower.',
  }),
  job({
    id: 'ea-ottawa',
    title: 'Executive Assistant to the Director',
    company: 'Civic Square Inc.',
    logoColor: GREEN,
    initials: 'CS',
    city: 'Ottawa',
    citySlug: 'ottawa',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: '3-5 Years',
    experienceSlug: '3-5-years',
    salaryMin: 68000,
    salaryMax: 82000,
    category: 'Executive Assistant',
    categorySlug: 'executive-assistant',
    employerSlug: 'td-bank-group',
    postedDate: '2026-07-28',
    description:
      'Manage a complex calendar, prepare briefing notes, and liaise with stakeholders in a high-visibility Ottawa office.',
  }),
  job({
    id: 'office-mgr-edmonton',
    title: 'Office Administrator',
    company: 'Yellowhead Workplace',
    logoColor: GOLD,
    initials: 'YW',
    city: 'Edmonton',
    citySlug: 'edmonton',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: '3-5 Years',
    experienceSlug: '3-5-years',
    salaryMin: 60000,
    salaryMax: 74000,
    category: 'Office Manager',
    categorySlug: 'office-manager',
    employerSlug: 'scotiabank',
    postedDate: '2026-07-26',
    description:
      'Run a well-organized Edmonton office including facilities, health and safety, and team events.',
  }),
  job({
    id: 'data-entry-toronto',
    title: 'Document Control Clerk',
    company: 'Lakeview Admin',
    logoColor: TEAL,
    initials: 'LA',
    city: 'Toronto',
    citySlug: 'toronto',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Contract',
    typeSlug: 'contract',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 46000,
    salaryMax: 54000,
    category: 'Data Entry',
    categorySlug: 'data-entry',
    employerSlug: 'rbc',
    postedDate: '2026-08-03',
    description:
      'Maintain version-controlled files, naming conventions, and audit-ready records for a professional services office.',
  }),
  job({
    id: 'cs-winnipeg',
    title: 'Client Services Assistant',
    company: 'Assiniboine Office Group',
    logoColor: NAVY,
    initials: 'AO',
    city: 'Winnipeg',
    citySlug: 'winnipeg',
    province: 'Manitoba',
    provinceCode: 'MB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 41000,
    salaryMax: 49000,
    category: 'Customer Service',
    categorySlug: 'customer-service',
    employerSlug: 'loblaw',
    postedDate: '2026-07-24',
    description:
      'Support walk-in clients, process forms, and keep service queues moving in a friendly Winnipeg office.',
  }),
  job({
    id: 'payroll-vancouver',
    title: 'Payroll & Benefits Clerk',
    company: 'Pacific Ledger',
    logoColor: GREEN,
    initials: 'PL',
    city: 'Vancouver',
    citySlug: 'vancouver',
    province: 'British Columbia',
    provinceCode: 'BC',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 54000,
    salaryMax: 66000,
    category: 'Payroll Clerk',
    categorySlug: 'payroll-clerk',
    employerSlug: 'telus',
    postedDate: '2026-07-22',
    description:
      'Administer payroll and benefits enrollments with attention to BC employment standards and confidentiality.',
  }),
  job({
    id: 'hr-calgary',
    title: 'HR Administrator',
    company: 'Rockies Talent Co.',
    logoColor: GOLD,
    initials: 'RT',
    city: 'Calgary',
    citySlug: 'calgary',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '3-5 Years',
    experienceSlug: '3-5-years',
    salaryMin: 62000,
    salaryMax: 76000,
    category: 'HR Support',
    categorySlug: 'hr-support',
    employerSlug: 'sun-life',
    postedDate: '2026-07-20',
    description:
      'Own HR administration from contracts to leave tracking for a growing Calgary professional services firm.',
  }),
  job({
    id: 'admin-edmonton-remote',
    title: 'Virtual Administrative Assistant',
    company: 'Northlight Support',
    logoColor: TEAL,
    initials: 'NS',
    city: 'Edmonton',
    citySlug: 'edmonton',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Part-time',
    typeSlug: 'part-time',
    mode: 'Remote',
    modeSlug: 'remote',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 40000,
    salaryMax: 50000,
    category: 'Administrative Assistant',
    categorySlug: 'administrative-assistant',
    employerSlug: 'td-bank-group',
    postedDate: '2026-08-19',
    description:
      'Provide remote inbox, scheduling, and document support to managers across Western Canada.',
  }),
  job({
    id: 'receptionist-vancouver',
    title: 'Lobby Concierge',
    company: 'Harbourfront Suites',
    logoColor: NAVY,
    initials: 'HS',
    city: 'Vancouver',
    citySlug: 'vancouver',
    province: 'British Columbia',
    provinceCode: 'BC',
    type: 'Temporary',
    typeSlug: 'temporary',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 39000,
    salaryMax: 45000,
    category: 'Receptionist',
    categorySlug: 'receptionist',
    employerSlug: 'telus',
    postedDate: '2026-08-18',
    description:
      'Temporary coverage for a premium Vancouver lobby: greet guests, book rooms, and keep the front of house polished.',
  }),
  job({
    id: 'ea-winnipeg',
    title: 'Executive Support Specialist',
    company: 'Prairie Executive Office',
    logoColor: GREEN,
    initials: 'PE',
    city: 'Winnipeg',
    citySlug: 'winnipeg',
    province: 'Manitoba',
    provinceCode: 'MB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '3-5 Years',
    experienceSlug: '3-5-years',
    salaryMin: 60000,
    salaryMax: 74000,
    category: 'Executive Assistant',
    categorySlug: 'executive-assistant',
    employerSlug: 'rbc',
    postedDate: '2026-07-18',
    description:
      'Blend executive support with light project coordination for a Winnipeg leadership team.',
  }),
  job({
    id: 'office-mgr-toronto',
    title: 'Workplace Coordinator',
    company: 'Queen Street Offices',
    logoColor: GOLD,
    initials: 'QS',
    city: 'Toronto',
    citySlug: 'toronto',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Contract',
    typeSlug: 'contract',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 53000,
    salaryMax: 64000,
    category: 'Office Manager',
    categorySlug: 'office-manager',
    employerSlug: 'scotiabank',
    postedDate: '2026-08-17',
    description:
      'Keep a downtown Toronto workplace stocked, scheduled, and visitor-ready on a 12-month contract.',
  }),
  job({
    id: 'data-ottawa',
    title: 'Data Processing Clerk',
    company: 'Byward Records',
    logoColor: TEAL,
    initials: 'BR',
    city: 'Ottawa',
    citySlug: 'ottawa',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 43000,
    salaryMax: 51000,
    category: 'Data Entry',
    categorySlug: 'data-entry',
    employerSlug: 'td-bank-group',
    postedDate: '2026-07-16',
    description:
      'Process high-volume forms with accuracy targets and supportive training for office newcomers.',
  }),
  job({
    id: 'cs-calgary',
    title: 'Office Customer Care Lead',
    company: 'Foothills Client Desk',
    logoColor: NAVY,
    initials: 'FC',
    city: 'Calgary',
    citySlug: 'calgary',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '5+ Years',
    experienceSlug: '5-plus-years',
    salaryMin: 64000,
    salaryMax: 78000,
    category: 'Customer Service',
    categorySlug: 'customer-service',
    employerSlug: 'sun-life',
    postedDate: '2026-07-14',
    description:
      'Lead a small office service team, coach on tone and process, and escalate complex client files.',
  }),
  job({
    id: 'payroll-ottawa',
    title: 'Junior Payroll Clerk',
    company: 'Parliament Payroll',
    logoColor: GREEN,
    initials: 'PP',
    city: 'Ottawa',
    citySlug: 'ottawa',
    province: 'Ontario',
    provinceCode: 'ON',
    type: 'Internship',
    typeSlug: 'internship',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 35000,
    salaryMax: 40000,
    category: 'Payroll Clerk',
    categorySlug: 'payroll-clerk',
    employerSlug: 'rbc',
    postedDate: '2026-08-19',
    description:
      'Learn payroll fundamentals while supporting timesheet audits and employee data updates.',
  }),
  job({
    id: 'hr-vancouver',
    title: 'HR Support Specialist',
    company: 'TELUS',
    logoColor: '#4B2E83',
    initials: 'T',
    city: 'Vancouver',
    citySlug: 'vancouver',
    province: 'British Columbia',
    provinceCode: 'BC',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Remote',
    modeSlug: 'remote',
    experience: '3-5 Years',
    experienceSlug: '3-5-years',
    salaryMin: 66000,
    salaryMax: 80000,
    category: 'HR Support',
    categorySlug: 'hr-support',
    employerSlug: 'telus',
    postedDate: '2026-07-12',
    description:
      'Deliver remote HR support including policy questions, onboarding, and employee file integrity.',
  }),
  job({
    id: 'admin-winnipeg',
    title: 'Administrative Assistant',
    company: 'Forks Business Centre',
    logoColor: GOLD,
    initials: 'FB',
    city: 'Winnipeg',
    citySlug: 'winnipeg',
    province: 'Manitoba',
    provinceCode: 'MB',
    type: 'Temporary',
    typeSlug: 'temporary',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: '1-3 Years',
    experienceSlug: '1-3-years',
    salaryMin: 44000,
    salaryMax: 52000,
    category: 'Administrative Assistant',
    categorySlug: 'administrative-assistant',
    employerSlug: 'loblaw',
    postedDate: '2026-08-15',
    description:
      'Six-month maternity cover supporting a Winnipeg office with scheduling, minutes, and travel.',
  }),
  job({
    id: 'receptionist-edmonton',
    title: 'Reception & Admin Clerk',
    company: 'Riverbend Offices',
    logoColor: TEAL,
    initials: 'RO',
    city: 'Edmonton',
    citySlug: 'edmonton',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: 'Entry Level',
    experienceSlug: 'entry-level',
    salaryMin: 40000,
    salaryMax: 47000,
    category: 'Receptionist',
    categorySlug: 'receptionist',
    employerSlug: 'td-bank-group',
    postedDate: '2026-07-10',
    description:
      'Blend reception duties with light admin including scanning, supplies, and meeting setup.',
  }),
  job({
    id: 'ea-calgary',
    title: 'Executive Assistant',
    company: 'Scotiabank',
    logoColor: '#D3222A',
    initials: 'S',
    city: 'Calgary',
    citySlug: 'calgary',
    province: 'Alberta',
    provinceCode: 'AB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'Hybrid',
    modeSlug: 'hybrid',
    experience: '5+ Years',
    experienceSlug: '5-plus-years',
    salaryMin: 75000,
    salaryMax: 92000,
    category: 'Executive Assistant',
    categorySlug: 'executive-assistant',
    employerSlug: 'scotiabank',
    postedDate: '2026-07-08',
    description:
      'Support senior bankers with complex calendars, client events, and confidential documentation.',
  }),
  job({
    id: 'office-mgr-winnipeg',
    title: 'Office Manager',
    company: 'Portage Place Admin',
    logoColor: NAVY,
    initials: 'PP',
    city: 'Winnipeg',
    citySlug: 'winnipeg',
    province: 'Manitoba',
    provinceCode: 'MB',
    type: 'Full-time',
    typeSlug: 'full-time',
    mode: 'On-site',
    modeSlug: 'on-site',
    experience: '5+ Years',
    experienceSlug: '5-plus-years',
    salaryMin: 64000,
    salaryMax: 79000,
    category: 'Office Manager',
    categorySlug: 'office-manager',
    employerSlug: 'sun-life',
    postedDate: '2026-07-06',
    description:
      'Lead a small facilities and admin team and own the day-to-day experience of a Winnipeg office.',
  }),
]
