export const SALES_CONTACT_TO = '/contact-us?subject=employer#contact-form'
export const GET_STARTED_TO = '/signup'

/** Employers page plans (teal cards, $149 / $299 / $599). */
export const employerPricingPlans = [
  {
    name: 'Starter',
    price: '$149',
    period: '/month',
    tagline: 'Perfect for small teams getting started.',
    features: [
      '3 Job Posts Included',
      '30-Day Applicant Access',
      'Standard Job Listing',
      'Employer Dashboard Access',
      'Email Support',
    ],
    ctaLabel: 'Get Started',
    ctaTo: GET_STARTED_TO,
    isFeatured: false,
  },
  {
    name: 'Growth',
    price: '$299',
    period: '/month',
    tagline: 'Ideal for growing businesses.',
    features: [
      '10 Job Posts Included',
      '60-Day Applicant Access',
      'Featured Job Listing',
      'Employer Dashboard Access',
      'Priority Email Support',
    ],
    ctaLabel: 'Get Started',
    ctaTo: GET_STARTED_TO,
    isFeatured: true,
  },
  {
    name: 'Enterprise',
    price: '$599',
    period: '/month',
    tagline: 'For companies with ongoing hiring needs.',
    features: [
      'Unlimited Job Posts',
      '90-Day Applicant Access',
      'Featured Company Profile',
      'Advanced Dashboard & Analytics',
      'Priority Phone & Email Support',
    ],
    ctaLabel: 'Contact Sales',
    ctaTo: SALES_CONTACT_TO,
    isFeatured: false,
  },
]

/** Post a Job plans (gold cards, $99 / $199 / $399). */
export const pricingPlans = [
  {
    slug: 'starter',
    name: 'Starter',
    price: '$99',
    period: '/month',
    tagline: 'Perfect for small teams and occasional hiring.',
    features: [
      '1 Job Post',
      'Standard Job Listing',
      '30-Day Listing Duration',
      'Applicant Access',
      'Employer Dashboard Access',
      'Email Support',
    ],
    ctaLabel: 'Get Started',
    ctaTo: '/post-a-job/create?plan=starter',
    isFeatured: false,
    highlighted: false,
  },
  {
    slug: 'growth',
    name: 'Growth',
    price: '$199',
    period: '/month',
    tagline: 'Great for growing companies hiring regularly.',
    features: [
      '5 Job Posts',
      { label: 'Featured Job Listing', badge: true },
      '30-Day Listing Duration',
      'Applicant Access',
      'Employer Dashboard Access',
      'Priority Email Support',
    ],
    ctaLabel: 'Get Started',
    ctaTo: '/post-a-job/create?plan=growth',
    isFeatured: true,
    highlighted: true,
  },
  {
    slug: 'enterprise',
    name: 'Enterprise',
    price: '$399',
    period: '/month',
    tagline: 'For teams with high-volume hiring needs.',
    features: [
      '20 Job Posts',
      { label: 'Featured Job Listing', badge: true },
      '60-Day Listing Duration',
      'Applicant Access',
      'Employer Dashboard Access',
      'Priority Support',
      'Custom Branding (Optional)',
    ],
    ctaLabel: 'Contact Sales',
    ctaTo: SALES_CONTACT_TO,
    isFeatured: false,
    highlighted: false,
  },
]
